# Website's icon url.
favicon: images/favicon.png

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

# Website's logo shown on the left of the navigation bar.
# It can either be an url to an image or a string if the following option is set.
# logo:
#   text: <logo string>
logo:
  text: Про буддизм

article:
  # Show word count and estimated reading time.
  readtime: false
  # Code highlight theme, please see https://highlightjs.org/static/demo/
  #highlight: atom-one-light

# Navigation bar menu links.
menu:
  Статьи: /Статьи
  Категории: /categories
  Задать вопрос: /Задать-вопрос
  Ссылки: /Ссылки
  #Видео: /Видео
  О проекте: /О-проекте

# Search plugin settings.
search:
  type: insight

# Navigation bar toc settings
toc: true

# Share plugin settings.
share:
  type: sharethis
  install_url: //platform-api.sharethis.com/js/sharethis.js#property=5e1c45d79913370013b307e4&product=inline-share-buttons&cms=sop

# Comment plugin settings.
comment:
  #type: disqus
  #shortname:

# Other plugins and their settings.
plugins:
  mathjax: false
  katex: false
  gallery: false
  clipboard: false
  google-analytics: false
    #tracking_id:

# Additional navigation bar links on the right.
# Links can either be text or icon. The following link is set to be an icon link whose icon
# is set to the class name of a FontAwesome 5 icon. The `footer_links` below also gives an
# example of setting plain text links.
navbar_links:
  #GitHub:
  #  icon: fab fa-github
  #  url: https://github.com/ppoffice/hexo-theme-minos

# Links at the bottom of the page.
footer_links:
  #GitHub: https://github.com/ppoffice/hexo-theme-minos
